apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgCC25wIMKggRwhuDRQ6dmXINDu3vowWbU0NTSz/GS2ODRUMRN7NXItRBpHNNB/cA/za0XEDQbiYtV2QzC/ABOzU3BqzWEBkFUeC1jmbfiBgqo0JpiYTFQeM5iQQsPUTdLVM06KnUYMAjBaHE7PhHIa8NzxXDQFk9JaXtwAKQVQlZt5qe4LUwEDjEQPbI6MOT9MMJoJNuOKenjTx9Hv+nydu3ZWWUK3InKCCjdpYQ7lJpZaKbjgD5jwyI8ixkBCgESSvT+kGFcUFp+TzyHQIp8UuwYg/WSOB+OYZrAd18grG0nbsbSzp2Nf5oYKKv4TYLHRGg9Eb/dWDgPti2rC9LRgy435lV+73w10HBfOGeheYzvGpQqQWkpGM08htUFxAskp2arVaBDYA5jQOhRjTCmSQW376me/TpQP63flyIEVNfr8mJ0ss7VJG4QSwl3JvfX+0EX8vBpe2iOqBS2aexl45zEfCH2UzdCpd8pRaPUzX8UtahV4i4GRJfDnCf6I2i7YCdq9cPFtmBiHSDPiqOggNtMmDoaNoHDxbfyjwye4dKeXB2qQB7mQ0ImguZ17ke35LAK0WwwLEuQKCkDUx9qnjN89qOAe8miBNTPX0l1y786bRsE1H0BIG4R2gdV7UW7HTGLT73UZ1T5d7hRilBJficTlc+xHkINQzdt6FbNqKDUr6J6oqmV0/c+cVJAAgOnTAO+HGSD7SPA==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

