apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgA2V7hv6HqtMHvxW3yemDhbxFBWC0ytGjdSWC8jNzHt1a0SdxycusZAiFxcc+oJokxSo4Wn/nzu4klmoisopD6Y8BCxITG3caiFh7IpDUzeTtA7xVo1zXhlb16OMjdZ0mDtI8XwUPwJdYoyRRAngPG5Qe3reo0ENQ75fyOwUKUkKwWdcF9uBVzNrARQi/5fYcgKvTHu0TD6Cd+qzsEquzFBaQmPWbU1AQGv4HanNPKrbLYL3s3XiE+mr/UoZdTlaqrT0sszRT2MjXlC6kU2oSgGlw5riBFnW3kAW2KZ+KsmErmkpxXcQQhF6cUbmm+AgnyPGIqrwczX7nVxnOBNV3Hm9cIj9cVhGAL1bdRIMVkOLncS5sfOSQO661OmywpZM2PzBGTpqlFlXR7yrb4NQBKei6VIdL8WfLhCO/oIYPiUueGk5nru7JzGYh+pR4mZhuJL+SB8Z9ybo3V/Z+8IFDDuY40kWpCNWO9L0L7eI1usi53EZ+s46xJIQ9lSze1jKvpds344RY2fsKkIzbaNNemnMBkDXUCEmcIPPU4zkFsODEAMt5eIbARcfgjnj5+lVvbFm7Mb1+fncRpu5QLuCY+bmRC7j4bMI/IiABx1OtV5bIZU1CQ+xLy2yWDz1Wbrg3QuZtqMLmywUrvY2+21kO/nnxJmeV6HSPZ/5gdy2SXvcFKcfgtwYFufrUaVCjXqgtHFf7SyMLLzog==
    DB_USER: AgAa352m5wbgTxMCekkPF+/F4TtES+3kEDwV7fxyDcpbIijLvbTnhmByzZAQSlacBCE3iz1JlX+GvsE9NK6Np+fCh6WrqqUrQI7dhvF2vbpRt92UyCyL3bcbuyarddZ+DrP8GOFg+Q9aqg6KNBuaXC8KuNY2VHKoh3l0rcrFH6v1568lQnSNnYx3vaY2ihZbXDJTxtg0U7+sQgREmyWYQCCI5OcM+79v0ukxe/BDIBTMidA2wbft8VwBw22EuYlvXOEwQk413KpNYNFSNJKOprbkD2O5F3e1TUf4NqPiCeTuPMenZYOCItMt0buV8wGWaRpj2592Zl06Wu+JG7s7c9oYMFQth2iAavnZRu5hVLFqbzU2se0m5QYn0CvmCSwH+sChGaoyej0a4Egf2Tln9mZaYA4jodmg+m6IuEB0k4h+H42CceoGnLqMwA5GPU5uamez1vq3DuYLNK1//RHfNvxfb5KgzvizpKBQQraRgP3N7Y58XWL6KMbNt8GODGQOudyM4KuvEPrDZzB/bUMWpZm2r3xy0yFub5Tp2WFRG1bDBb9JnUyFpEnk7+is0GVJEKSalgpBbU/BW7yVBX/s+WWtOwjxXR1NEbwxCgJSngKUu/mBkZvxS4+7F0wzgriK3Mg9ZRUmBKrLexVQpMrf1BO0GAoioKxBvgAELk/xi53ZS3+ZpiDIOp8mnl9ISqV2KNWLCI4IqByPXQ==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

