apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgBNZtt0uyejvHc5h8f3FhF5Arw0BFxrT/jKB56XbSx1bkfC0T/7I8Of1MVw10ftqWriwulcnh9//+Os98pcADvNbp0eSejby/PgWhfLsB1zp3zurLdktqLK/QeaXMNpvZeNPgSaq1rh0deT/xYWz2z34zWVObgvi2G6un3+21KAInAARGcpC2WtB0Eul+08Ud3fRLfI+efdDmyoT14c2tvdixZTcznxWAXpyjF6yNr3NNMbKDOqcRoctQH9hO7x8luAe4Uz43UxMk7f8UVYy2DBddHK0yVgdwCJyaS75LaGAx/8p32CCOyAAzRafBCMEOn9dDe/0RNsYu84FNns/AaVyk1hrlRKflfQfcommB8wHH/6ejq525eus+aSQID15yLVQGxw4Jol3Y0xxRxq0FFX2tREYZ8d1qXdKdXDBv3dMyi2/i8bpDxfTXq/OLZ1qVaUiVhwe3YN/7kMEvLp1RAjkLjUnhp4QPyG/Getw6ySowCXCYS52BHtujrFoVuVHi7+/OjuvoF5i4zjjdQjiwYD+ZE8hPNdOVmci5iweQqObCUljy7FRjEPopzQTMefK5G6qAfbsyDB2FwBgrAyn5blkMFJLxO/atLKgLee6blMI00ykrxaZ1lfHEmj8X6HrsZRikQqp46F6mlESZDDtFIINEukdFv7K7dW+barmdqjxNE0Q8pGyaUBkeoEzZze0Zqi+AsEQuvf2g==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

